kind: Event
apiVersion: audit.k8s.io/v1
level: RequestResponse
timestamp: "2024-02-29T22:30:00Z"
auditID: d7e8f9g0-h1i2-j3k4-l5m6-n7o8p9q0r1s2
stage: ResponseComplete
requestURI: "/apis/networking.k8s.io/v1/namespaces/default/networkpolicies"
verb: "list"
user:
  username: "system:serviceaccount:default:andromeda-service-account"
sourceIPs: ["10.244.2.2"]
responseObject:
  kind: NetworkPolicyList
  apiVersion: networking.k8s.io/v1
annotations:
  kubernetes.io/network-boundary-bridging: "Attempted enumeration of network policies to identify zero-trust boundary weaknesses."
responseStatus:
  code: 200