kind: Event
apiVersion: audit.k8s.io/v1
level: RequestResponse
timestamp: "2024-03-01T00:10:00Z"
auditID: y7z8a9b0-c1d2-e3f4-g5h6-i7j8k9l0m1n2
stage: ResponseComplete
requestURI: "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings"
verb: "create"
user:
  username: "system:serviceaccount:linked:compromised-service-account"
sourceIPs: ["10.244.4.5"]
responseObject:
  kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: "cross-environment-access-binding"
annotations:
  kubernetes.io/pass-the-role: "Created a ClusterRoleBinding 'cross-environment-access-binding' using a compromised role to assume additional roles within the EKS cluster."
responseStatus:
  code: 201